description: "This portofilo page created to learn to build project
websites in GitHub with GitHub Pages."
email: "rawan20181997@hotmail.com"

remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme
